// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SmsServerClient is the client API for SmsServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SmsServerClient interface {
}

type smsServerClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsServerClient(cc grpc.ClientConnInterface) SmsServerClient {
	return &smsServerClient{cc}
}

// SmsServerServer is the server API for SmsServer service.
// All implementations must embed UnimplementedSmsServerServer
// for forward compatibility
type SmsServerServer interface {
	mustEmbedUnimplementedSmsServerServer()
}

// UnimplementedSmsServerServer must be embedded to have forward compatible implementations.
type UnimplementedSmsServerServer struct {
}

func (*UnimplementedSmsServerServer) mustEmbedUnimplementedSmsServerServer() {}

func RegisterSmsServerServer(s *grpc.Server, srv SmsServerServer) {
	s.RegisterService(&_SmsServer_serviceDesc, srv)
}

var _SmsServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sms.v1.SmsServer",
	HandlerType: (*SmsServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/sms/v1/sms.proto",
}
