// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v4.25.1
// source: api/sms/v1/sms.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationSmsServerDeleteOrder = "/sms.v1.SmsServer/DeleteOrder"

type SmsServerHTTPServer interface {
	DeleteOrder(context.Context, *CreateTemplateRequest) (*emptypb.Empty, error)
}

func RegisterSmsServerHTTPServer(s *http.Server, srv SmsServerHTTPServer) {
	r := s.Route("/")
	r.DELETE("/v1/orders", _SmsServer_DeleteOrder0_HTTP_Handler(srv))
}

func _SmsServer_DeleteOrder0_HTTP_Handler(srv SmsServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTemplateRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationSmsServerDeleteOrder)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteOrder(ctx, req.(*CreateTemplateRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type SmsServerHTTPClient interface {
	DeleteOrder(ctx context.Context, req *CreateTemplateRequest, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type SmsServerHTTPClientImpl struct {
	cc *http.Client
}

func NewSmsServerHTTPClient(client *http.Client) SmsServerHTTPClient {
	return &SmsServerHTTPClientImpl{client}
}

func (c *SmsServerHTTPClientImpl) DeleteOrder(ctx context.Context, in *CreateTemplateRequest, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/v1/orders"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationSmsServerDeleteOrder))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
