// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameConfigurationM = "sms_configuration"

// ConfigurationM mapped from table <sms_configuration>
type ConfigurationM struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfigKey    string    `gorm:"column:config_key;not null" json:"config_key"`
	ConfigValue  string    `gorm:"column:config_value;not null" json:"config_value"`
	TemplateCode string    `gorm:"column:template_code;not null" json:"template_code"`
	CreatedAt    time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ConfigurationM's table name
func (*ConfigurationM) TableName() string {
	return TableNameConfigurationM
}
