// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameHistoryM = "sms_history"

// HistoryM mapped from table <sms_history>
type HistoryM struct {
	ID                int32     `gorm:"column:id;primaryKey" json:"id"`
	Mobile            string    `gorm:"column:mobile" json:"mobile"`
	SendTime          time.Time `gorm:"column:send_time" json:"send_time"`
	ConsumerID        string    `gorm:"column:consumer_id" json:"consumer_id"`
	Status            string    `gorm:"column:status" json:"status"`
	Content           string    `gorm:"column:content" json:"content"`
	Code              string    `gorm:"column:code" json:"code"`
	Message           string    `gorm:"column:message" json:"message"`
	MessageID         string    `gorm:"column:message_id" json:"message_id"`
	MessageTemplateID int64     `gorm:"column:message_template_id" json:"message_template_id"`
	CreateAt          time.Time `gorm:"column:create_at" json:"create_at"`
	UpdateAt          time.Time `gorm:"column:update_at" json:"update_at"`
}

// TableName HistoryM's table name
func (*HistoryM) TableName() string {
	return TableNameHistoryM
}
