// Copyright 2022 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://"github.com/rosas99/monster.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: api/usercenter/v1/usercenter.proto

package v1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const ()

// UserCenterServerClient is the client API for UserCenterServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserCenterServerClient interface {
}

type userCenterServerClient struct {
	cc grpc.ClientConnInterface
}

func NewUserCenterServerClient(cc grpc.ClientConnInterface) UserCenterServerClient {
	return &userCenterServerClient{cc}
}

// UserCenterServerServer is the server API for UserCenterServer service.
// All implementations must embed UnimplementedUserCenterServerServer
// for forward compatibility
type UserCenterServerServer interface {
	mustEmbedUnimplementedUserCenterServerServer()
}

// UnimplementedUserCenterServerServer must be embedded to have forward compatible implementations.
type UnimplementedUserCenterServerServer struct {
}

func (UnimplementedUserCenterServerServer) mustEmbedUnimplementedUserCenterServerServer() {}

// UnsafeUserCenterServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserCenterServerServer will
// result in compilation errors.
type UnsafeUserCenterServerServer interface {
	mustEmbedUnimplementedUserCenterServerServer()
}

func RegisterUserCenterServerServer(s grpc.ServiceRegistrar, srv UserCenterServerServer) {
	s.RegisterService(&UserCenterServer_ServiceDesc, srv)
}

// UserCenterServer_ServiceDesc is the grpc.ServiceDesc for UserCenterServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserCenterServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.v1.UserCenterServer",
	HandlerType: (*UserCenterServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/usercenter/v1/usercenter.proto",
}
